pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('Amazon') {
                    sh 'mvn clean package'
                }
            }
        }
    }

    post {
        success {
            emailext (
                to: 'harshithayadav809@gmail.com',
                subject: "SUCCESS: ${env.JOB_NAME}",
                body: "Build Success: ${env.BUILD_URL}"
            )
        }

        failure {
            emailext (
                to: 'your_email@gmail.com',
                subject: "FAILED: ${env.JOB_NAME}",
                body: "Build Failed: ${env.BUILD_URL}"
            )
        }
    }
}
