post {
    success {
        mail to: 'harshithayadav809@gmail.com',
             subject: 'SUCCESS',
             body: "Build Passed: ${env.BUILD_URL}"
    }
    failure {
        mail to: 'harshithayadav809@gmail.com',
             subject: 'FAILED',
             body: "Build Failed: ${env.BUILD_URL}"
    }
}
